#!/bin/bash
# TIL Complete Image Download
# Run from INSIDE your repo: bash download-images.sh
# (You're already in teloislandlodge, no cd needed)

mkdir -p assets/philanthropy assets/boards

echo "========================================"
echo "  TIL Image Download"
echo "========================================"

echo ""
echo "--- Lodge page hero + angles ---"
curl -sS -o assets/lodge-hero.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/Tilo_Lodge_Beachfront.jpg"
curl -sS -o assets/lodge-relaxation.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/Telo_Lodge_Relaxation.jpg"
curl -sS -o assets/lodge-night.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/Telo_Lodge_Night.jpg"
curl -sS -o assets/lodge-bedroom.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/Telo_Lodge_Bedroom_Oceanview-1.jpg"
echo "  ✓ 4 lodge images"

echo ""
echo "--- History page sunset ---"
curl -sS -o assets/telo-sunset.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/Telo-sunsets-PNT17.jpg"
echo "  ✓ telo-sunset.jpg"

echo ""
echo "--- TIL icon ---"
curl -sS -o assets/til-icon.png "https://pegasuslodges.com/wp-content/uploads/2018/03/telo-island-icon-1.png"
echo "  ✓ til-icon.png"

echo ""
echo "--- Lost Surfboards ---"
curl -sS -o assets/boards/el-patron.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/ElPatron-2.jpg"
curl -sS -o assets/boards/crowd-killer.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/CrowdKiller-2.jpg"
curl -sS -o assets/boards/puddle-jumper-hp.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/PuddleJumperHP-1.jpg"
curl -sS -o assets/boards/rnf-redux.jpg "https://pegasuslodges.com/wp-content/uploads/2019/07/RNFRedux-1.jpg"
echo "  ✓ 4 board images"

echo ""
echo "--- Philanthropy / Sibaranun Village ---"
curl -sS -o assets/philanthropy/village-overview.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/village3.jpeg"
curl -sS -o assets/philanthropy/church.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-church.jpeg"
curl -sS -o assets/philanthropy/convent.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-churchconvent.jpeg"
curl -sS -o assets/philanthropy/classroom-1.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-classroom2.jpeg"
curl -sS -o assets/philanthropy/classroom-2.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-classroom.jpeg"
curl -sS -o assets/philanthropy/classroom-roof.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-classroomroof.jpeg"
curl -sS -o assets/philanthropy/mama-bella.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-coconutoillady.jpeg"
curl -sS -o assets/philanthropy/local-enterprise.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-independentbuisness.jpeg"
curl -sS -o assets/philanthropy/mask-maker.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-masklady.jpeg"
curl -sS -o assets/philanthropy/kids-crafts.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-masklady2.jpeg"
curl -sS -o assets/philanthropy/mask-shop.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-masklady3.jpeg"
curl -sS -o assets/philanthropy/kids-teacher.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-school3.jpeg"
curl -sS -o assets/philanthropy/kids-happy.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-school2.jpeg"
curl -sS -o assets/philanthropy/school.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-school.jpeg"
curl -sS -o assets/philanthropy/kids-playing.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-schoolkids.jpeg"
curl -sS -o assets/philanthropy/village-houses.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-village-1.jpeg"
# Extra 3 from PNT philanthropy page
curl -sS -o assets/philanthropy/village-old.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-village4.jpeg"
curl -sS -o assets/philanthropy/village-domestic.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-village5.jpeg"
curl -sS -o assets/philanthropy/village-palms.jpeg "https://pegasuslodges.com/wp-content/uploads/2019/08/Telo-Island-Lodge-Philanthropy-Sibaranun-Village-village6.jpeg"
echo "  ✓ 19 philanthropy images"

echo ""
echo "========================================"
echo "  DONE"
echo "========================================"
echo ""
echo "  Lodge:          $(ls assets/lodge-*.jpg 2>/dev/null | wc -l | tr -d ' ') files"
echo "  History:         $(ls assets/telo-sunset.jpg 2>/dev/null | wc -l | tr -d ' ') file"
echo "  Logo:            $(ls assets/til-icon.png 2>/dev/null | wc -l | tr -d ' ') file"
echo "  Boards:          $(ls assets/boards/*.jpg 2>/dev/null | wc -l | tr -d ' ') files"
echo "  Philanthropy:    $(ls assets/philanthropy/*.jpeg 2>/dev/null | wc -l | tr -d ' ') files"
echo "  SUP:             already added"
echo "  Logos from Drive: already pushed"
echo ""
echo "Homepage hero: already in repo as assets/hero.jpg"
echo "History hero: uses assets/telo-sunset.jpg (just downloaded)"
echo ""
echo "Next: git add assets/ && git commit -m 'Add all imagery' && git push origin main"
